spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
  servlet:
    context-path: /

# Configuración CORS para producción
app:
  security:
    cors:
      allowed-origins:
        - "https://nanai-kit.vercel.app"
        - "https://nanai-kit-git-main-nanai-kit.vercel.app"
        - "https://nanai-kit-git-develop-nanai-kit.vercel.app"
      allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
        - "PATCH"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
