# Configuración específica para CORS
spring:
  web:
    cors:
      allowed-origins: "https://nanai-kit.vercel.app,https://nanai-kit-git-main-nanai-kit.vercel.app,https://nanai-kit-git-develop-nanai-kit.vercel.app,http://localhost:3000,http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# Configuración del servidor
server:
  port: 8080
  servlet:
    context-path: /

# Logging para debug de CORS
logging:
  level:
    org.springframework.web.cors: DEBUG
    com.nanai_kit.security.config: DEBUG
